In [1]:
# Import all packages and dependencies
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import sys, warnings, os
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from IPython.core.display import HTML, display

In [2]:
# Read in the dataset
df = pd.read_csv("../Resources/data_preprocessed.csv")
df.head()

,index,Winner,title_bout,lose_streak_dif,win_streak_dif,longest_win_streak_dif,win_dif,loss_dif,total_round_dif,total_title_bout_dif,...,tot_str_attempted_bout_diff,td_landed_bout_diff,td_attempted_bout_diff,td_pct_bout_diff,sub_attempts_bout_diff,pass_bout_diff,rev_bout_diff,Stance_diff,better_rank_enc,level_0
0,0,0,0,0,-1,-7,-27,-13,-57,-1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,-1,0
1,1,1,0,0,0,0,12,7,80,9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,-1,1
2,2,1,0,-1,0,-3,-6,-3,-21,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,-1,2
3,3,0,0,0,-1,-1,5,2,15,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,-1,3
4,4,0,0,-1,0,0,6,3,29,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,4

In [3]:
# Read in the dataset
df1 = pd.read_csv("../Resources/upcoming_data_preprocessed.csv")
df1

,Winner,title_bout,lose_streak_dif,win_streak_dif,longest_win_streak_dif,win_dif,loss_dif,total_round_dif,total_title_bout_dif,ko_dif,...,tot_str_landed_bout_diff,tot_str_attempted_bout_diff,td_landed_bout_diff,td_attempted_bout_diff,td_pct_bout_diff,sub_attempts_bout_diff,pass_bout_diff,rev_bout_diff,Stance_diff,better_rank_enc
0,NaN,1,0.0,-6.0,-6.0,0.0,3.0,-7.0,-3.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,-1
1,NaN,0,-1.0,1.0,-3.0,0.0,2.0,8.0,0.0,-4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,-1
2,NaN,0,-3.0,1.0,-2.0,-6.0,-4.0,-30.0,-1.0,-1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,-1
3,NaN,0,0.0,-1.0,-2.0,0.0,2.0,-2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2,0
4,NaN,0,-1.0,0.0,1.0,0.0,-2.0,-3.0,0.0,-1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
5,NaN,0,1.0,-2.0,-1.0,-1.0,2.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
6,NaN,0,0.0,0.0,-1.0,-4.0,2.0,-13.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,-1
7,NaN,0,0.0,0.0,0.0,0.0,-2.0,-2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
8,NaN,0,0.0,1.0,1.0,-1.0,-1.0,-5.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0
9,NaN,0,-1.0,1.0,1.0,1.0,-1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0
10,NaN,0,-1.0,1.0,-1.0,-5.0,-3.0,-17.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,0

In [4]:
# Delete previously unknown data so we can manually insert who won
wins = ["Winner"]
df1.drop(wins, axis=1, inplace=True)

In [5]:
# Create list for the winners of previously unkown fights and reinsert the Winner column
win = [
    1,
    0,
    1,
    1,
    0,
    0,
    1,
    1,
    0,
    1,
    0
]
df1.insert(0, "Winner", win)

In [6]:
df2 = pd.read_csv("../Resources/comparison.csv")
df2.head()

,R_fighter,B_fighter,gender,R_age,B_age,R_Height_cms,B_Height_cms,R_Weight_lbs,B_Weight_lbs,R_Reach_cms,B_Reach_cms,sig_str_landed_bout_diff,ev_diff,odds_diff,tot_str_landed_bout_diff,sig_str_pct_bout_diff
0,Alistair Overeem,Alexander Volkov,MALE,40,32,193.04,200.66,265,250,203.20,203.20,0,-95.054945,-332,0,0.0
1,Cory Sandhagen,Frankie Edgar,MALE,28,39,180.34,167.64,135,135,177.80,172.72,0,275.000000,700,0,0.0
2,Alexandre Pantoja,Manel Kape,MALE,30,27,165.10,165.10,125,125,170.18,172.72,0,20.000000,225,0,0.0
3,Diego Ferreira,Beneil Dariush,MALE,36,31,175.26,177.80,155,155,187.96,182.88,0,25.000000,230,0,0.0
4,Michael Johnson,Clay Guida,MALE,34,39,177.80,170.18,155,155,185.42,177.80,0,130.555556,400,0,0.0

In [7]:
# Index is only needed for SQL join so we must drop it here so it doesnt effect outcomes
index = ['index', 'level_0']
df.drop(index, axis=1, inplace = True)

In [8]:
df.head()

,Winner,title_bout,lose_streak_dif,win_streak_dif,longest_win_streak_dif,win_dif,loss_dif,total_round_dif,total_title_bout_dif,ko_dif,...,tot_str_landed_bout_diff,tot_str_attempted_bout_diff,td_landed_bout_diff,td_attempted_bout_diff,td_pct_bout_diff,sub_attempts_bout_diff,pass_bout_diff,rev_bout_diff,Stance_diff,better_rank_enc
0,0,0,0,-1,-7,-27,-13,-57,-1,-17,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,-1
1,1,0,0,0,0,12,7,80,9,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,-1
2,1,0,-1,0,-3,-6,-3,-21,0,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,-1
3,0,0,0,-1,-1,5,2,15,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,-1
4,0,0,-1,0,0,6,3,29,0,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0

In [9]:
X = df.drop(['Winner'], axis=1)
y= df.Winner

In [10]:
# Split dataset into train test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size = 0.25)

In [11]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [12]:
rf_model = RandomForestClassifier(random_state=42)

In [13]:
# Fit the model w the training data
rf_model.fit(X_train_scaled, y_train)

RandomForestClassifier(random_state=42)

In [14]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)
acc_score = accuracy_score(y_test, predictions)

In [15]:
print(acc_score)

0.7784588441330998

In [16]:
# Assign Variable and Label for unseen data
var = df1.drop(['Winner'], axis=1)
lab = df1.Winner

In [17]:
# Make predictions with unseen data and get an accuracy score
pred = rf_model.predict(var)
ac_sco = accuracy_score(lab, pred)

In [18]:
# The new model predicted the unseen data with 72% accuracy on a sample size of 11, which means we 
# can reasonably justify that the model is not overfit to our dataset
print(ac_sco)
print(pred)

0.7272727272727273
[1 1 1 1 0 1 1 0 0 1 0]

In [23]:
sorted(zip(pred, df1.Winner), reverse=True)

[(1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 0),
 (1, 0),
 (0, 1),
 (0, 0),
 (0, 0),
 (0, 0)]